### ISSUE TITLE
nuxt: Unexpected token <

### ISSUE THREAD

**Issue by tchret** [P3trur0/vue-country-flag#10]
![image](https://user-images.githubusercontent.com/4539476/59429435-7ec0bb80-8de8-11e9-9330-04530c8c4ff6.png)

**Comment by P3trur0** [comment]
Hi @tchret, could you detail the error a little more, please?

**Comment by opichon** [comment]
[vue-router] Failed to resolve async component default: SyntaxError: Unexpected token <
[vue-router] uncaught error during route navigation:
/Users/olivier/projects/dzango.com/www/node_modules/vue-country-flag/CountryFlag.vue:1
<template>
^

SyntaxError: Unexpected token <
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at r (/Users/olivier/projects/dzango.com/www/node_modules/vue-server-renderer/build.js:8360:16)
    at Object.<anonymous> (server-bundle.js:2316:18)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.<anonymous> (0.server-bundle.js:546:75)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.<anonymous> (0.server-bundle.js:537:191)
    at __webpack_require__ (server-bundle.js:27:30)
    at Object.<anonymous> (0.server-bundle.js:1545:96)
    at __webpack_require__ (server-bundle.js:27:30)
error during render : /
/Users/olivier/projects/dzango.com/www/node_modules/vue-country-flag/CountryFlag.vue:1
<template>
^

SyntaxError: Unexpected token <
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at r (/Users/olivier/projects/dzango.com/www/node_modules/vue-server-renderer/build.js:8360:16)
    at Object.<anonymous> (webpack:/external "vue-country-flag":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap cfa7b7c94d8b68de6b4d:25:0)
    at Object.<anonymous> (0.server-bundle.js:546:75)
    at __webpack_require__ (webpack:/webpack/bootstrap cfa7b7c94d8b68de6b4d:25:0)
    at Object.<anonymous> (src/modules/home/_components/Contact.vue?c0b3:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap cfa7b7c94d8b68de6b4d:25:0)
    at Object.<anonymous> (src/modules/home/_components/Contact.vue:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap cfa7b7c94d8b68de6b4d:25:0)

**Comment by P3trur0** [comment]
@opichon thanks for the log, I'll give it a look.
Just to confirm my understanding here: did you notice the issue while building with Webpack and this component embedded in as dependency?

**Comment by opichon** [comment]
The component was embedded inside another Vue component
```
import VueCountryFlag from 'vue-country-flag`

export default {

  components: {
    CountryFlag
  }
}
```
(approximately only, since I've now removed the component).
The app is built with Webpack.

**Comment by P3trur0** [comment]
@opichon I am trying to reproduce your problem, but at the moment, even using Webpack, in my samples the component renders properly.  

Do you have any environment with your Webpack configuration setup? That would be helpful to further investigate the problem.

Thank you!

**Comment by opichon** [comment]
Here is the package.json file
```json
{
  "name": "xxxx",
  "version": "2.0.3",
  "private": true,
  "scripts": {
    "dev": "node server",
    "start": "cross-env NODE_ENV=production node server",
    "build": "rimraf dist && npm run build:client && npm run build:server",
    "build:client": "cross-env NODE_ENV=production webpack --config build/webpack.client.config.js --progress --hide-modules",
    "build:server": "cross-env NODE_ENV=production webpack --config build/webpack.server.config.js --progress --hide-modules",
    "fix": "eslint --ext .js,.vue src --fix",
    "lint": "eslint --ext .js,.vue src"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free": "^5.6.3",
    "aos": "^2.3.4",
    "apollo-cache-inmemory": "^1.3.12",
    "apollo-client": "^2.4.8",
    "apollo-link": "^1.2.6",
    "apollo-link-http": "^1.5.9",
    "bootstrap": "^4.2.1",
    "bootstrap-vue": "^2.0.0-rc.11",
    "compression": "^1.7.1",
    "cookie-parser": "^1.4.3",
    "cross-env": "^5.1.1",
    "dotenv": "^6.2.0",
    "es6-promise": "^4.1.1",
    "express": "^4.16.2",
    "extract-text-webpack-plugin": "^3.0.2",
    "firebase": "4.6.2",
    "graphql": "^14.0.2",
    "graphql-tag": "^2.10.0",
    "lru-cache": "^4.1.1",
    "marked": "^0.6.1",
    "node-fetch": "^2.3.0",
    "route-cache": "0.4.3",
    "serve-favicon": "^2.4.5",
    "vue": "^2.5.16",
    "vue-apollo": "^3.0.0-beta.27",
    "vue-country-flag": "^1.2.2",
    "vue-i18n": "^7.4.2",
    "vue-router": "^3.0.1",
    "vue-server-renderer": "^2.5.16",
    "vuex": "^3.0.1",
    "vuex-router-sync": "^5.0.0"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.6",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^7.1.2",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "babel-preset-env": "^1.6.1",
    "chokidar": "^1.7.0",
    "css-loader": "^0.28.7",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-html": "^4.0.3",
    "eslint-plugin-import": "^2.11.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.7.0",
    "eslint-plugin-standard": "^3.1.0",
    "file-loader": "^1.1.5",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "node-sass": "^4.9.0",
    "rimraf": "^2.6.2",
    "sass-loader": "^7.1.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "sw-precache-webpack-plugin": "^0.11.4",
    "url-loader": "^0.6.2",
    "vue-loader": "^15.0.0-beta.1",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^3.8.1",
    "webpack-dev-middleware": "^1.12.0",
    "webpack-hot-middleware": "^2.20.0",
    "webpack-merge": "^4.1.1",
    "webpack-node-externals": "^1.6.0"
  },
  "engines": {
    "node": ">= 10.0.0",
    "npm": ">= 6.0.0"
  },
  "license": "UNLICENSED"
}
```

**Comment by P3trur0** [comment]
@opichon thank you, may I read also your webpack config? Thank you 😄

**Comment by P3trur0** [comment]
@tchret @opichon an updated version of the component is available on NPM. It is a built version of the component as a minified SFC available in three different flavours:

- UNPKG version (see [https://unpkg.com/vue-country-flag@1.2.3](https://unpkg.com/vue-country-flag@1.2.3))
- ES module
- SSR

Please, have a look. This might resolve this issue too.

**Comment by rubennaatje** [comment]
Just in case you wanted to know, this works for me in Nuxt. :)
